license_id: "cc-by-igo"
caveats: "More details about the indicators are available in the links in the dataset description."
methodology: "Registry"
dataset_source: "World Health Organization"
package_creator: "mcarans"
private: False  # has to be True or False
