license_id: "hdx-other"
license_other: "Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Intergovernmental Organization (CC BY-NC-SA 3.0 IGO). Click [here](https://www.who.int/about/who-we-are/publishing-policies/copyright) for more information."
caveats: "More details about the indicators are available in the links in the dataset description."
methodology: "Registry"
dataset_source: "World Health Organization"
package_creator: "mcarans"
private: False  # has to be True or False
