license_id: "cc-by-igo"
subnational: 1  # has to be 0 or 1
notes: "Contains data from World Health Organization's [data portal](http://www.who.int/gho/en/) covering various indicators (one per resource)."
caveats: "More details about the indicators are available in the links in the resource descriptions."
methodology: "Registry"
dataset_source: "World Health Organization"
package_creator: "mcarans"
private: False  # has to be True or False
url: ~
state: "active"  # always "active".
