# Collector specific configuration
base_url: "https://ghoapi.azureedge.net/"
category_url: "https://xmart-api-public.who.int/"
qc_indicators:
  - code: 'WHOSIS_000001'
    title: "Life Expectancy at Birth"
    unit: "Years"
    description: "Number of years of life expectancy at birth"
    aggregate_col: "#dimension+code"
  - code: 'MDG_0000000001'
    title: "Infant Mortality Rate"
    unit: "Percent"
    description: "Probability of dying between birth and age 1 per 1000 live births"
    aggregate_col: "#dimension+code"
  - code: 'WHOSIS_000015'
    title: "Life expectancy at age 60 (years)"
    unit: "Years"
    description: "Life expectancy at age 60 (years)"
    aggregate_col: "#dimension+name"
