# Collector specific configuration
base_url: "https://ghoapi.azureedge.net/"
category_url: "https://xmart-api-public.who.int/"
qc_indicators:
  - code: ""
    title: "Life Expectancy at Birth"
    unit: "Years"
    description: "Number of years of life expectancy at birth"
    aggregate_col: "#indicator+value"
